export const IS_LOADING = "IS_LOADING";
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_OTP_TOKEN = "SET_OTP_TOKEN";

export const SHOW_CHATINPUT_ADD_MODAL = "SHOW_CHATINPUT_ADD_MODAL";
export const SET_SELETED_MESSAGE = "SET_SELETED_MESSAGE";
export const SHOW_EMOJI_MODAL = "SHOW_EMOJI_MODAL";

export const SET_CHAT_HISTORY = "SET_CHAT_HISTORY";
export const SET_MESSAGES = "SET_MESSAGES";
export const ACTIVE_CHAT = "ACTIVE_CHAT";
export const ADD_ONE_MESSAGE = "ADD_ONE_MESSAGE";
export const SET_EDIT_MESSAGE = "SET_EDIT_MESSAGE";
export const UPDATE_EDITED_MESSAGE = "UPDATE_EDITED_MESSAGE";
export const DELETE_MESSAGE_MODAL_VISIBLE = "DELETE_MESSAGE_MODAL_VISIBLE";
export const UPDATE_DELETE_MESSAGE = "UPDATE_DELETE_MESSAGE";
export const SET_CONTACT_LIST = "SET_CONTACT_LIST";
// export const SET_OTP_TOKEN = 'SET_OTP_TOKEN';
// export const SET_OTP_TOKEN = 'SET_OTP_TOKEN';
