export const IMAGES = {
    logoChat: require('./logoChat.png'),
    introImage: require('./introImage.png'),
    rightArrow: require('./rightArrow.png'),
    userInput: require('./userInput.png'),
    passwordInput: require('./passwordInput.png'),
    bottomArrow: require('./bottomArrow.png'),
    otpInput: require('./otpInput.png'),
    successInput: require('./successInput.png'),
    usernameInput: require('./usernameInput.png'),
    callingInput: require('./callingInput.png'),
    wrong: require('./wrong.png'),
    right: require('./right.png'),
    updateImage: require('./updateImage.png'),
    calender: require('./calender.png'),
    imagePlaceholder: require('./imagePlaceholder.png'),
    storiesIcon: require('./storiesIcon.png'),
    tabBG: require('./tabBG.png'),
    call: require('./call.png'),
    contacts: require('./contacts.png'),
    homeTab: require('./homeTab.png'),
    chatIcon: require('./chatIcon.png'),
    liveIcon: require('./liveIcon.png'),
    userImage: require('./userImage.png'),
    location: require('./location.png'),
    moreMenu: require('./moreMenu.png'),
    searchIcon: require('./searchIcon.png'),
    deleteIcon: require('./deleteIcon.png'),
    // introImage:require('./introImage.png'),
    // introImage:require('./introImage.png'),
    // introImage:require('./introImage.png'),
    // introImage:require('./introImage.png'),
    // introImage:require('./introImage.png'),
    // introImage:require('./introImage.png'),
    // introImage:require('./introImage.png'),

}